#ifndef CONSTANTS_H
#define CONSTANTS_H

#define KEY_ASSET              QLatin1String("asset")
#define KEY_GENERATOR          QLatin1String("generator")
#define KEY_VERSION            QLatin1String("version")
#define KEY_CAMERA             QLatin1String("camera")
#define KEY_CAMERAS            QLatin1String("cameras")
#define KEY_SCENES             QLatin1String("scenes")
#define KEY_NODES              QLatin1String("nodes")
#define KEY_MESHES             QLatin1String("meshes")
#define KEY_CHILDREN           QLatin1String("children")
#define KEY_MESH               QLatin1String("mesh")
#define KEY_MATRIX             QLatin1String("matrix")
#define KEY_TYPE               QLatin1String("type")
#define KEY_PERSPECTIVE        QLatin1String("perspective")
#define KEY_ORTHOGRAPHIC       QLatin1String("orthographic")
#define KEY_NAME               QLatin1String("name")
#define KEY_COUNT              QLatin1String("count")
#define KEY_YFOV               QLatin1String("yfov")
#define KEY_ZNEAR              QLatin1String("znear")
#define KEY_ZFAR               QLatin1String("zfar")
#define KEY_XMAG               QLatin1String("xmag")
#define KEY_YMAG               QLatin1String("ymag")
#define KEY_MATERIALS          QLatin1String("materials")
#define KEY_EXTENSIONS         QLatin1String("extensions")
#define KEY_EXTENSIONS_USED    QLatin1String("extensionsUsed")
#define KEY_EXTENSIONS_REQ     QLatin1String("extensionsRequired")
#define KEY_BUFFERS            QLatin1String("buffers")
#define KEY_ACCESSORS          QLatin1String("accessors")
#define KEY_SCENE              QLatin1String("scene")
#define KEY_BUFFER             QLatin1String("buffer")
#define KEY_TARGET             QLatin1String("target")
#define KEY_BYTE_OFFSET        QLatin1String("byteOffset")
#define KEY_BYTE_LENGTH        QLatin1String("byteLength")
#define KEY_BYTE_STRIDE        QLatin1String("byteStride")
#define KEY_PRIMITIVES         QLatin1String("primitives")
#define KEY_MODE               QLatin1String("mode")
#define KEY_MATERIAL           QLatin1String("material")
#define KEY_ATTRIBUTES         QLatin1String("attributes")
#define KEY_INDICES            QLatin1String("indices")
#define KEY_BUFFER_VIEWS       QLatin1String("bufferViews")
#define KEY_BUFFER_VIEW        QLatin1String("bufferView")
#define KEY_COMPONENT_TYPE     QLatin1String("componentType")
#define KEY_ASPECT_RATIO       QLatin1String("aspectRatio")

#define KEY_EXT_DRACO_COMP     QLatin1String("KHR_draco_mesh_compression")

#endif // CONSTANTS_H
